services:
  web:
    build: .
    command: gunicorn social_media_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A social_media_api worker --loglevel=info
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      