# Generated by Django 4.2.30 on 2026-05-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='follower',
            new_name='followers',
        ),
    ]
