# Generated by Django 4.2.30 on 2026-05-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_users', 'Can view users'), ('can_create_users', 'Can create users'), ('can_edit_users', 'Can edit users'), ('can_delete_users', 'Can delete users')]},
        ),
    ]
