from rest_framework import viewsets, permissions, filters,status
from django.contrib.contenttypes.models import ContentType
from .models import Post, Comment,Like
from .serializers import PostSerializer, CommentSerializer
from .pagination import PostCommentPagination
from notifications.models import Notification
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from notifications.utils import create_notification



class IsAuthorOrReadOnly(permissions.BasePermission):
    
    def has_object_permission(self, request, view, obj):
        if request.method in permissions.SAFE_METHODS:
            return True

        return obj.author == request.user


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all().order_by("-created_at")
    serializer_class = PostSerializer
    permission_classes = [IsAuthorOrReadOnly,permissions.IsAuthenticated]

    pagination_class = PostCommentPagination

    filter_backends = [filters.SearchFilter]
    search_fields = ["title", "content"]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class CommentViewSet(viewsets.ModelViewSet):
    serializer_class = CommentSerializer
    permission_classes = [
        IsAuthorOrReadOnly,
        permissions.IsAuthenticated
    ]

    pagination_class = PostCommentPagination

    def get_queryset(self):
        queryset = Comment.objects.all().order_by("-created_at")

        post_id = self.request.query_params.get("post")

        if post_id:
            queryset = queryset.filter(post_id=post_id)

        return queryset


class LikePostView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)

        like, created = Like.objects.get_or_create(
            user=request.user,
            post=post,
        )

        if not created:
            return Response(
                {"detail": "You have already liked this post."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        create_notification(
            recipient=post.author,
            actor=request.user,
            verb="liked your post",
            target=post,
        )

        return Response(
            {"detail": "Post liked successfully."},
            status=status.HTTP_201_CREATED,
        )

class UnlikePostView(APIView):
    permission_classes = [IsAuthenticated]

    def delete(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)

        like = Like.objects.filter(
            user=request.user,
            post=post,
        ).first()

        if not like:
            return Response(
                {"detail": "You have not liked this post."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        like.delete()

        # Remove the notification generated by this like
        content_type = ContentType.objects.get_for_model(post)

        Notification.objects.filter(
            recipient=post.author,
            actor=request.user,
            verb="liked your post",
            target_content_type=content_type,
            target_object_id=post.id,
        ).delete()

        return Response(
            {"detail": "Post unliked successfully."},
            status=status.HTTP_200_OK,
        )
    